import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  parseTranscriptLines,
  extractTitle,
  extractCurrentActivity,
  extractPrLinks,
  extractLastActivityAt,
  extractAwaitingInput,
  extractLastMessage,
  summarizeTranscript,
} from '../src/cc-transcript.js';

function jl(...objs) {
  return objs.map((o) => JSON.stringify(o)).join('\n') + '\n';
}

test('parseTranscriptLines tolerates blank and malformed lines', () => {
  const text = '{"type":"user"}\n\n  \n{bad json}\n{"type":"system"}\n';
  const lines = parseTranscriptLines(text);
  assert.equal(lines.length, 2);
  assert.equal(lines[0].type, 'user');
  assert.equal(lines[1].type, 'system');
});

test('extractTitle returns the first real user prompt (string content)', () => {
  const lines = parseTranscriptLines(
    jl(
      { type: 'system', subtype: 'init' },
      { type: 'user', message: { role: 'user', content: '帮我修复登录 bug' }, timestamp: '2026-06-06T03:11:47.847Z' },
      { type: 'assistant', message: { role: 'assistant', content: [{ type: 'text', text: 'ok' }] } },
      { type: 'user', message: { role: 'user', content: '继续' } },
    ),
  );
  assert.equal(extractTitle(lines), '帮我修复登录 bug');
});

test('extractTitle skips tool_result array content and meta/command wrappers', () => {
  const lines = parseTranscriptLines(
    jl(
      { type: 'user', message: { role: 'user', content: [{ type: 'tool_result', content: 'x' }] } },
      { type: 'user', message: { role: 'user', content: '<command-name>/effort</command-name>' } },
      { type: 'user', message: { role: 'user', content: '<system-reminder>hi</system-reminder>' } },
      { type: 'user', message: { role: 'user', content: 'Caveat: generated by a local command' } },
      { type: 'user', message: { role: 'user', content: '真正的问题在这里' } },
    ),
  );
  assert.equal(extractTitle(lines), '真正的问题在这里');
});

test('extractTitle truncates very long prompts to a max length', () => {
  const long = 'x'.repeat(400);
  const lines = parseTranscriptLines(jl({ type: 'user', message: { role: 'user', content: long } }));
  const title = extractTitle(lines, { maxLength: 120 });
  assert.ok(title.length <= 121, `expected <=121 got ${title.length}`);
  assert.ok(title.endsWith('…'));
});

test('extractCurrentActivity prefers the latest last-prompt line', () => {
  const lines = parseTranscriptLines(
    jl(
      { type: 'user', message: { role: 'user', content: 'first prompt' } },
      { type: 'last-prompt', lastPrompt: 'first prompt' },
      { type: 'user', message: { role: 'user', content: '推送+开 PR 给 Codex 复评' } },
      { type: 'last-prompt', lastPrompt: '推送+开 PR 给 Codex 复评' },
    ),
  );
  assert.equal(extractCurrentActivity(lines), '推送+开 PR 给 Codex 复评');
});

test('extractCurrentActivity falls back to last real user message when no last-prompt', () => {
  const lines = parseTranscriptLines(
    jl(
      { type: 'user', message: { role: 'user', content: 'only prompt' } },
      { type: 'assistant', message: { role: 'assistant', content: [{ type: 'text', text: 'reply' }] } },
    ),
  );
  assert.equal(extractCurrentActivity(lines), 'only prompt');
});

test('extractPrLinks dedupes by number, keeps the latest, sorted ascending', () => {
  const lines = parseTranscriptLines(
    jl(
      { type: 'pr-link', prNumber: 249, prUrl: 'u249a', prRepository: 'acme/app', timestamp: '2026-06-01T05:23:15.764Z' },
      { type: 'pr-link', prNumber: 249, prUrl: 'u249b', prRepository: 'acme/app', timestamp: '2026-06-01T05:23:28.812Z' },
      { type: 'pr-link', prNumber: 210, prUrl: 'u210', prRepository: 'acme/app', timestamp: '2026-05-30T00:00:00.000Z' },
    ),
  );
  const prs = extractPrLinks(lines);
  assert.equal(prs.length, 2);
  assert.deepEqual(prs.map((p) => p.number), [210, 249]);
  assert.equal(prs.find((p) => p.number === 249).url, 'u249b'); // latest kept
  assert.equal(prs[1].repository, 'acme/app');
});

test('extractPrLinks: a later pr-link without a timestamp still overrides an earlier one', () => {
  const lines = parseTranscriptLines(
    jl(
      { type: 'pr-link', prNumber: 7, prUrl: 'old', prRepository: 'o/r', timestamp: '2026-06-01T00:00:00.000Z' },
      { type: 'pr-link', prNumber: 7, prUrl: 'new', prRepository: 'o/r' }, // no timestamp, later in file
    ),
  );
  const prs = extractPrLinks(lines);
  assert.equal(prs.length, 1);
  assert.equal(prs[0].url, 'new');
});

test('extractLastActivityAt returns the max timestamp in ms', () => {
  const lines = parseTranscriptLines(
    jl(
      { type: 'user', message: { role: 'user', content: 'a' }, timestamp: '2026-06-06T03:11:47.000Z' },
      { type: 'system', subtype: 'away', timestamp: '2026-06-06T05:44:58.000Z' },
      { type: 'last-prompt', lastPrompt: 'no timestamp here' },
    ),
  );
  assert.equal(extractLastActivityAt(lines), Date.parse('2026-06-06T05:44:58.000Z'));
});

test('extractAwaitingInput is true when last assistant text ends with a question', () => {
  const lines = parseTranscriptLines(
    jl(
      { type: 'user', message: { role: 'user', content: 'do it' } },
      { type: 'assistant', message: { role: 'assistant', content: [{ type: 'text', text: 'want me to push and open the PR, or leave it local?' }] } },
      { type: 'system', subtype: 'turn_duration', timestamp: '2026-06-06T05:38:48.000Z' },
    ),
  );
  assert.equal(extractAwaitingInput(lines), true);
});

test('extractAwaitingInput is false when last assistant text is a statement', () => {
  const lines = parseTranscriptLines(
    jl(
      { type: 'assistant', message: { role: 'assistant', content: [{ type: 'text', text: 'Done. All tests pass.' }] } },
    ),
  );
  assert.equal(extractAwaitingInput(lines), false);
});

test('extractAwaitingInput is false when the user already replied after the question', () => {
  const lines = parseTranscriptLines(
    jl(
      { type: 'assistant', message: { role: 'assistant', content: [{ type: 'text', text: '要我推送吗?' }] } },
      { type: 'user', message: { role: 'user', content: '推送吧' } },
    ),
  );
  assert.equal(extractAwaitingInput(lines), false);
});

test('extractLastMessage returns the most recent message with its role', () => {
  const userLast = parseTranscriptLines(
    jl(
      { type: 'assistant', message: { role: 'assistant', content: [{ type: 'text', text: 'done?' }] } },
      { type: 'user', message: { role: 'user', content: '继续推送' } },
    ),
  );
  assert.deepEqual(extractLastMessage(userLast), { role: 'user', text: '继续推送' });

  const asstLast = parseTranscriptLines(
    jl(
      { type: 'user', message: { role: 'user', content: '开始' } },
      { type: 'assistant', message: { role: 'assistant', content: [{ type: 'text', text: '已完成所有测试。' }] } },
    ),
  );
  assert.deepEqual(extractLastMessage(asstLast), { role: 'assistant', text: '已完成所有测试。' });
});

test('extractLastMessage skips trailing tool_result / non-message lines', () => {
  const lines = parseTranscriptLines(
    jl(
      { type: 'assistant', message: { role: 'assistant', content: [{ type: 'text', text: '我来跑测试' }] } },
      { type: 'user', message: { role: 'user', content: [{ type: 'tool_result', content: 'output' }] } },
      { type: 'last-prompt', lastPrompt: 'x' },
      { type: 'system', subtype: 'turn_duration' },
    ),
  );
  assert.deepEqual(extractLastMessage(lines), { role: 'assistant', text: '我来跑测试' });
});

const asstText = (t) => ({ type: 'assistant', message: { role: 'assistant', content: [{ type: 'text', text: t }] } });
const asstTool = (id) => ({ type: 'assistant', message: { role: 'assistant', stop_reason: 'tool_use', content: [{ type: 'tool_use', id, name: 'Bash' }] } });
const toolResult = (id) => ({ type: 'user', message: { role: 'user', content: [{ type: 'tool_result', tool_use_id: id, content: 'ok' }] } });
const userText = (t) => ({ type: 'user', message: { role: 'user', content: t } });

test('awaitingInput: assistant text ending in ? → true (unchanged)', () => {
  assert.equal(extractAwaitingInput([asstText('Shall I proceed?')]), true);
});

test('awaitingInput: user replied after the question → false (unchanged)', () => {
  assert.equal(extractAwaitingInput([asstText('Proceed?'), userText('yes')]), false);
});

test('awaitingInput: pending tool_use (awaiting permission) → true', () => {
  assert.equal(extractAwaitingInput([asstText('Running a command'), asstTool('t1')]), true);
});

test('awaitingInput: tool_use resolved by tool_result, normal end → false', () => {
  assert.equal(extractAwaitingInput([asstTool('t1'), toolResult('t1'), asstText('Done.')]), false);
});

test('awaitingInput: user typed a new prompt after an unresolved tool_use → false', () => {
  assert.equal(extractAwaitingInput([asstTool('t1'), userText('do something else')]), false);
});

test('summarizeTranscript composes the fields from raw text', () => {
  const text = jl(
    { type: 'user', message: { role: 'user', content: '开场提问' }, timestamp: '2026-06-06T03:00:00.000Z' },
    { type: 'assistant', message: { role: 'assistant', content: [{ type: 'text', text: '继续吗?' }] }, timestamp: '2026-06-06T03:05:00.000Z' },
    { type: 'last-prompt', lastPrompt: '最新提问' },
    { type: 'pr-link', prNumber: 7, prUrl: 'u7', prRepository: 'o/r', timestamp: '2026-06-06T03:04:00.000Z' },
  );
  const s = summarizeTranscript(text);
  assert.equal(s.title, '开场提问');
  assert.equal(s.currentActivity, '最新提问');
  assert.equal(s.prLinks.length, 1);
  assert.equal(s.awaitingInput, true);
  assert.equal(s.lastActivityAt, Date.parse('2026-06-06T03:05:00.000Z'));
  assert.deepEqual(s.lastMessage, { role: 'assistant', text: '继续吗?' });
});
